name = "DanielIngrahamRegistry"
uuid = "5f7f95a9-53dc-4914-bd15-5a5a3c36d23e"
repo = "git@developer.nasa.gov:dingraha/DanielIngrahamRegistry.git"

[packages]
046f749b-9c1e-43ca-86bc-6902340f753e = { name = "AcousticMetrics", path = "A/AcousticMetrics" }
24d19c10-6eee-420f-95df-4537264b2753 = { name = "OpenMDAOCore", path = "O/OpenMDAOCore" }
5dd5ea32-d67d-426d-b4ce-2ad113187929 = { name = "SingleFieldStructArrays", path = "S/SingleFieldStructArrays" }
60a40a53-6d8e-4940-bfcb-6c86f9d3795d = { name = "NZawodny2016Propeller", path = "N/NZawodny2016Propeller" }
6a4a75d9-c98f-4276-9eff-70e8e993a339 = { name = "ANOPP2", path = "A/ANOPP2" }
730d3219-0a85-48f9-b699-9f31f8913d09 = { name = "KinematicCoordinateTransformations", path = "K/KinematicCoordinateTransformations" }
a110648e-2308-4a5e-af40-0e5e4b5cf51d = { name = "LitMan", path = "L/LitMan" }
cd5ebc29-f022-437d-affb-ff7a1ae69623 = { name = "CF1A", path = "C/CF1A" }
dfba9b08-b01a-4e4c-a288-371e2cdee4ea = { name = "CROTORCCBladeComparisons", path = "C/CROTORCCBladeComparisons" }
e71b3392-1e0c-4536-b366-2bd1fce6fba0 = { name = "AcousticAnalogies", path = "A/AcousticAnalogies" }
